# Numpy Matrix Operation

### Matrix 만들기

In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Column추출

In [2]:
arr_data=arr[:,0:2]
arr_data

array([[1, 2],
       [4, 5],
       [7, 8]])

In [3]:
arr_label=arr[:,2:3]
arr_label

array([[3],
       [6],
       [9]])

### 합치기 
#### 열(column) 합치기

In [4]:
np.hstack([arr_data,arr_label])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 행(row) 합치기

In [5]:
arr1=np.array([[11,12],[13,14],[15,16]])
arr2=np.array([[21,22],[23,24],[25,26]])
np.vstack([arr1,arr2])


array([[11, 12],
       [13, 14],
       [15, 16],
       [21, 22],
       [23, 24],
       [25, 26]])