# Numpy instrospection

In [ ]:
import math

In [ ]:
dir(math)

In [ ]:
import numpy as np

In [ ]:
dir(np)

In [ ]:
help(np.array)

In [ ]:
# dir(np)
print('\n'.join([s for s in dir(np) if s.find('array') >= 0 ]))


# Operation
## Plus 연산

In [ ]:
a1=np.array([1, 2, 3])
a2=np.array([1, 1, 1])
a1+a2

array([2, 3, 4])

## Dot product

In [ ]:
a1=np.array([[1, 2],[3,4]])
a2=np.array([[2, 0],[0,2]])
# a1*a2
np.dot(a1,a2)

array([[2, 4],
       [6, 8]])

# Cf) join, for-in 문

In [ ]:
#dir("x")
"x".join(['1','2','3'])

'1x2x3'

In [ ]:
[i*2 for i in range(10) if i%2 == 0 ]

[0, 4, 8, 12, 16]

# Shape

In [ ]:
a1=np.array([[1, 2, 3],[4,5,6]])
a1.shape


(2, 3)

# Reshape

In [ ]:
a2=np.array(range(12))
a2.reshape((3,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Random

In [ ]:
help(np.random.randn)

In [ ]:
dir(np.random)

In [ ]:
m=np.random.randn( 2,3)
print(m)

array([[-0.28527233, -0.9911214 , -1.33260328],
       [-0.29944731,  1.74138343, -0.34192414]])

# 방정식 풀기

In [ ]:
#help(np.linalg.inv)
np.linalg.inv(np.array([[2, 0],
                        [0, 2]]))

array([[0.5, 0. ],
       [0. , 0.5]])

In [ ]:
# y=2x+1, y=-x+1
a=np.array([[1, -2],[1,1]])

ai= np.linalg.inv(a)
np.dot(ai,np.array([[1],[4]]))



array([[3.],
       [1.]])