# [Preprocessing data](https://scikit-learn.org/stable/modules/preprocessing.html)

## Scale
* 각 컬럼의 평균이 0이 되고, 표준편차가 1이 되게 함

In [36]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])
X_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [37]:
X_scaled = preprocessing.scale(X_train,axis=0)

X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [38]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [39]:
X_scaled.std(axis=0)

array([1., 1., 1.])

# Normalization
* 값을 고르게 분포 시킴
* Concept 
  - http://hleecaster.com/ml-normalization-concept/
  - https://developers.google.com/machine-learning/crash-course/regularization-for-simplicity/l2-regularization?hl=ko



In [35]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized


array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [22]:

X_normalized.sum(axis=0)


array([1.40824829, 0.29885849, 0.1093898 ])

In [13]:
X_normalized.std(axis=0)

array([0.41053309, 0.46075826, 0.62254262])