In [ ]:
import numpy as np
import pandas as pd

# 연습해봅시다. 

In [ ]:
l=range(12)
a1=np.array(l)
print(a1)
print(a1.shape)
print(a1.reshape(3,4)  )

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a2=np.array([1,2])
print(a2.dtype)
print(a2[1].__class__)

int64
<class 'numpy.int64'>


In [ ]:
a2=np.array([1.,2.])
print(a2.dtype)
print(a2[1].__class__)

float64
<class 'numpy.float64'>


In [ ]:
(1+2j)*(1+3j)

(-5+5j)

In [ ]:
a2=np.array([(1+2j),(1+3j)])
print(a2.dtype)
print(a2[1].__class__)

complex128
<class 'numpy.complex128'>


In [ ]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Encoder Example
enc=np.eye(3) 
l=[0,2,1,0]
l_enc=[enc[i] for i in l]
# [[ 1.,  0.,  0.],
#  [ 0.,  0.,  1.],
#  [ 0.,  1.,  0.],
#  [ 1.,  0.,  0.]]
print(l_enc)



[array([1., 0., 0.]), array([0., 0., 1.]), array([0., 1., 0.]), array([1., 0., 0.])]


In [ ]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [ ]:
 np.ones((2,2))*7

array([[7., 7.],
       [7., 7.]])

In [ ]:
a=np.array([1,2,3])
l=[1,2,3]
t=(1,2,3)
l[0]=11 # 수정가능
#t[0]=11 # 수정불가
print(l*2)
# print(l**2)
print(a*2)
print(a**2)

[11, 2, 3, 11, 2, 3]
[2 4 6]
[1 4 9]


In [ ]:
help(slice)

Help on class slice in module builtins:

class slice(object)
 |  slice(stop)
 |  slice(start, stop[, step])
 |  
 |  Create a slice object.  This is used for extended slicing (e.g. a[0:10:2]).
 |  
 |  Methods defined here:
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  indices(...)
 |      S.indices(len) -> (start, stop, stride)
 |      
 | 

In [ ]:
l=range(20)
l[3:4]
for i in l[3:6]:
    print(i)
[i for i in l[0:10:3]]

3
4
5


[0, 3, 6, 9]

In [ ]:
a1=np.array(range(12)).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1[1:3,]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

In [ ]:
a1[(1,2),]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1[:,(0,3)]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [ ]:
a1=np.array(range(100)).reshape(10,10)
a1


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# 1. 주변만 빼고 알맹이만.
a1[1:9,1:9]

array([[11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26, 27, 28],
       [31, 32, 33, 34, 35, 36, 37, 38],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [51, 52, 53, 54, 55, 56, 57, 58],
       [61, 62, 63, 64, 65, 66, 67, 68],
       [71, 72, 73, 74, 75, 76, 77, 78],
       [81, 82, 83, 84, 85, 86, 87, 88]])

In [ ]:
# 2. 1,3,5,7,9번째 컬럼을 추출하시오. 
#a1[:,1:10:2]
a1[:,(1,3,5,7,9)]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [ ]:
a1=np.array(range(90)).reshape(9,10)
(r,c)=a1.shape
a1[1:r-1,1:c-1]

# 초보용
s=a1.shape
a1[1:s[0]-1,1:s[1]-1]




array([[11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26, 27, 28],
       [31, 32, 33, 34, 35, 36, 37, 38],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [51, 52, 53, 54, 55, 56, 57, 58],
       [61, 62, 63, 64, 65, 66, 67, 68],
       [71, 72, 73, 74, 75, 76, 77, 78]])

In [ ]:
a1=np.array(range(1,7)).reshape(3,2)
a1    

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a1[0]

array([1, 2])

In [ ]:
a1[0][0]

1

In [ ]:
a1[[0,0,1]]

array([[1, 2],
       [1, 2],
       [3, 4]])

In [ ]:
a1[[0,0,1],[0,1,0]]

array([1, 2, 3])

In [ ]:
a1[1:2,]

array([[3, 4]])

In [ ]:
a1[:,1:2]

array([[2],
       [4],
       [6]])

In [ ]:
data=np.array([1,2,3,4])
# 위치 index
idx=np.array([0,3])
print(data[idx])
# Bool index
bidx=np.array([True,False,False,True])
print(data[bidx])


[1 4]
[1 4]


In [ ]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [ ]:
np.repeat(x, 3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [ ]:
np.repeat(x, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
np.tile(x, (2, 2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [ ]:
import numpy as np
xarr = np.array([11,1,-1,1,1])
# >10, <0  으면 이상치, 이상치이면 10, 0으로 조정
def outlier_corret(su):
    if su>10:
        return 10
    elif su<0:
        return 0
    else:
        return su
yarr = np.array([10,0,0,0,0])
result = [outlier_corret(i) for i in xarr ]    
print(result)
cond = np.array([False, True, False, True, True])

result = np.where(cond, xarr, yarr)

[10, 1, 0, 1, 1]


In [ ]:
result

array([10,  1,  0,  1,  1])

In [ ]:
a1=np.array([4,3,2,1]).reshape(2,2)
print(a1)
a1.sort(1)
print(a1)
a1.sort(0)
print(a1)



[[4 3]
 [2 1]]
[[3 4]
 [1 2]]
[[1 2]
 [3 4]]


In [ ]:
help(a1.sort)

Help on built-in function sort:

sort(...) method of numpy.ndarray instance
    a.sort(axis=-1, kind='quicksort', order=None)
    
    Sort an array, in-place.
    
    Parameters
    ----------
    axis : int, optional
        Axis along which to sort. Default is -1, which means sort along the
        last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. Default is 'quicksort'.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still be used, in the order in which
        they come up in the dtype, to break ties.
    
    See Also
    --------
    numpy.sort : Return a sorted copy of an array.
    argsort : Indirect sort.
    lexsort : Indirect stable sort on multiple keys.
    searchsorted :

In [ ]:
a1=np.array(range(12)).reshape(-1,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Save

In [ ]:
np.save('a1',a1)

In [ ]:
np.savetxt('a1.txt',a1,fmt='%d',delimiter=',',header='c1,c2,c3')

In [ ]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

# Test/Train data 나누기

In [ ]:
import numpy
# x is your dataset
x = numpy.array(range(20)).reshape(10,-1)
numpy.random.shuffle(x)
x
training, test = x[:8,:], x[8:,:]

training

array([[14, 15],
       [16, 17],
       [ 6,  7],
       [ 8,  9],
       [12, 13],
       [ 2,  3],
       [10, 11],
       [18, 19]])

In [ ]:
test

array([[0, 1],
       [4, 5]])