In [1]:
import numpy as np
labels=['setosa','versicolor','verginica']
for i in enumerate(labels):
  print(i)

  

(0, 'setosa')
(1, 'versicolor')
(2, 'verginica')


In [3]:
ohenc=np.identity(3)
ohenc

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
ohenc[1]

array([0., 1., 0.])

In [5]:
{i:"a" for i in range(3)}

{0: 'a', 1: 'a', 2: 'a'}

In [6]:
{k:v for v,k in enumerate(labels)}

{'setosa': 0, 'verginica': 2, 'versicolor': 1}

In [7]:
enc={k:ohenc[v] for v,k in enumerate(labels)}

In [8]:
enc['setosa']

array([1., 0., 0.])

In [9]:
l=['setosa','versicolor','verginica','setosa','versicolor','setosa',]
ohl=[enc[i] for i in l]
ohl

[array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([1., 0., 0.])]