In [14]:
import numpy as np
labels=['setosa','versicolor','verginica']
for i in enumerate(labels):
  print(i)

  

(0, 'setosa')
(1, 'versicolor')
(2, 'verginica')


In [0]:
ohenc=np.identity(3)
ohenc[1]

In [0]:
{i:"a" for i in range(3)}

In [15]:
{k:v for v,k in enumerate(labels)}

{'setosa': 0, 'verginica': 2, 'versicolor': 1}

In [0]:
enc={k:ohenc[v] for v,k in enumerate(labels)}

In [18]:
enc['setosa']

array([1., 0., 0.])

In [20]:
l=['setosa','versicolor','verginica','setosa','versicolor','setosa',]
ohl=[enc[i] for i in l]
ohl

[array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([1., 0., 0.])]