Trains a simple deep NN on the IRIS dataset.



In [41]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop

In [42]:
batch_size = 50
num_classes = 3
epochs = 200

In [43]:
import pandas as pd
!wget http://j.finfra.com/_file/iris.csv
iris=pd.read_csv("iris.csv")
iris.drop(['no'],1,inplace=True)
iris

--2020-08-02 14:50:50--  http://j.finfra.com/_file/iris.csv
Resolving j.finfra.com (j.finfra.com)... 211.252.85.187
Connecting to j.finfra.com (j.finfra.com)|211.252.85.187|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4374 (4.3K) [text/csv]
Saving to: ‘iris.csv.2’

iris.csv.2          100%[===================>]   4.27K  --.-KB/s    in 0s      

2020-08-02 14:50:50 (440 MB/s) - ‘iris.csv.2’ saved [4374/4374]



Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [44]:
iris.iloc[:,4:5]

Species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [45]:
iriss=iris.sample(frac=1).reset_index(drop=True)
iriss

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
0             4.5          2.3           1.3          0.3      setosa
1             5.5          2.3           4.0          1.3  versicolor
2             7.7          2.6           6.9          2.3   virginica
3             5.1          3.8           1.9          0.4      setosa
4             5.4          3.4           1.7          0.2      setosa
..            ...          ...           ...          ...         ...
145           6.9          3.1           5.1          2.3   virginica
146           7.3          2.9           6.3          1.8   virginica
147           5.5          2.4           3.7          1.0  versicolor
148           6.2          2.9           4.3          1.3  versicolor
149           4.4          3.2           1.3          0.2      setosa

[150 rows x 5 columns]

In [46]:
# Shuffling
iriss=iris.sample(frac=1).reset_index(drop=True)
iris_train=iriss.iloc[0:100,:]
iris_test=iriss.iloc[100:150,:]

x_train=iris_train.iloc[:,0:4].values
x_test=iris_test.iloc[:,0:4].values
y_train=iris_train.iloc[:,4:5]
y_test= iris_test.iloc[:,4:5]
# encoder={k:v for v,k in enumerate(y_train.drop_duplicates())}
# encoder
sets=iris.iloc[:,4:5].drop_duplicates()["Species"].tolist()
encoder={k:v for v,k in enumerate(sets)}
y_train=[ encoder[i] for i in y_train["Species"].tolist() ]
y_train = keras.utils.to_categorical(y_train, num_classes)

y_test=[ encoder[i] for i in y_test["Species"].tolist() ]
y_test = keras.utils.to_categorical(y_test, num_classes)

In [47]:
y_test


array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1

In [48]:
# 데이터 shape 을 확인해 봅니다.
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(100, 4) (100, 3) (50, 4) (50, 3)


In [49]:
model = Sequential()
model.add(Dense(4, activation='relu', input_shape=(4,)))
#model.add(Dropout(0.2))
model.add(Dense(5, activation='relu'))
#model.add(Dropout(0.2))
model.add(Dense(5, activation='relu'))
#model.add(Dropout(0.2))

model.add(Dense(num_classes, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_6 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 18        
Total params: 93
Trainable params: 93
Non-trainable params: 0
_________________________________________________________________


In [50]:
import  tensorflow.keras.optimizers
dir( tensorflow.keras.optimizers)

['Adadelta',
 'Adagrad',
 'Adam',
 'Adamax',
 'Ftrl',
 'Nadam',
 'Optimizer',
 'RMSprop',
 'SGD',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'deserialize',
 'get',
 'schedules',
 'serialize']

In [51]:
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))


Epoch 1/200
2/2 [==============================] - 0s 56ms/step - loss: 1.1254 - accuracy: 0.1300 - val_loss: 1.1110 - val_accuracy: 0.3800
Epoch 2/200
2/2 [==============================] - 0s 15ms/step - loss: 1.1130 - accuracy: 0.3100 - val_loss: 1.1040 - val_accuracy: 0.3800
Epoch 3/200
2/2 [==============================] - 0s 15ms/step - loss: 1.1051 - accuracy: 0.3100 - val_loss: 1.0988 - val_accuracy: 0.3800
Epoch 4/200
2/2 [==============================] - 0s 15ms/step - loss: 1.0980 - accuracy: 0.3100 - val_loss: 1.0941 - val_accuracy: 0.3800
Epoch 5/200
2/2 [==============================] - 0s 15ms/step - loss: 1.0919 - accuracy: 0.3100 - val_loss: 1.0899 - val_accuracy: 0.3800
Epoch 6/200
2/2 [==============================] - 0s 15ms/step - loss: 1.0864 - accuracy: 0.3100 - val_loss: 1.0859 - val_accuracy: 0.3800
Epoch 7/200
2/2 [==============================] - 0s 14ms/step - loss: 1.0811 - accuracy: 0.3100 - val_loss: 1.0820 - val_accuracy: 0.3800
Epoch 8/200
2/2 [===

In [52]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.42628347873687744
Test accuracy: 0.9800000190734863


In [53]:
model.predict(x_test[:3,:])

array([[9.6015412e-01, 3.9638583e-02, 2.0725584e-04],
       [9.6428120e-01, 3.5552859e-02, 1.6595726e-04],
       [5.9138678e-02, 2.8408724e-01, 6.5677398e-01]], dtype=float32)

In [54]:
model.predict_classes(x_test[:3,:])

array([0, 0, 2])

In [55]:
y_test[:3,:]

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)